name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update && sudo apt-get install -y jq

      - name: Validate manifest version
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/v}
          MANIFEST_VERSION=$(jq -r '.version' custom_components/ha_vodarenska/manifest.json)
          echo "Git tag: $VERSION_TAG"
          echo "Manifest version: $MANIFEST_VERSION"
          if [ "$VERSION_TAG" != "$MANIFEST_VERSION" ]; then
            echo "❌ Version mismatch: tag=$VERSION_TAG manifest=$MANIFEST_VERSION"
            exit 1
          fi
          echo "✅ Version OK ($VERSION_TAG)"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
